# @package _global_

defaults:
  - challenge: default
  - workflow_orchestration: default
  - _self_
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default

# Main configuration
question: "What is machine learning and how does it work?"

# Basic settings
retries: 3
manual_confirm: false

# Challenge configuration
challenge:
  enabled: false
  name: "Research Challenge"
  domain: "general"

# Workflow orchestration configuration
workflow_orchestration:
  enabled: true  # Enable the primary REACT workflow orchestration
  primary_workflow:
    workflow_type: primary_react
    name: main_research_workflow
    enabled: true
    priority: 10
    max_retries: 3
    timeout: 300.0
    parameters:
      max_iterations: 10
      enable_reflection: true
      enable_self_correction: true
      coordination_strategy: adaptive
      enable_sub_workflow_spawning: true
      enable_dynamic_composition: true
      enable_multi_agent_coordination: true

# Legacy flow configurations (for backward compatibility)
flows:
  prime:
    enabled: false
  bioinformatics:
    enabled: false
  rag:
    enabled: false
  deepsearch:
    enabled: false
  node_example:
    enabled: false
  jina_ai:
    enabled: false

# Output configuration
outputs:
  enable_hypothesis_datasets: true
  enable_testing_environments: true
  enable_reasoning_results: true
  enable_automated_datasets: true
  output_format: structured_json
  include_metadata: true
  include_execution_traces: true

# Performance settings
performance:
  enable_parallel_execution: true
  enable_result_caching: true
  cache_ttl: 3600  # 1 hour
  enable_workflow_optimization: true